[package]
name = "gr-module-probe-assets"
version.workspace = true
edition.workspace = true
build = "build.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
gr-abi = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
parking_lot = { workspace = true }

[features]
default = []
plugin = []
