//! R100 authenticity templates — SSOT load + JS render for pseudo-static delivery.
//!
//! Product path:
//!   brain schedules 1× `Rxx_spotcheck` / tick
//!   → FE loads static `registry.random.rt.js` once
//!   → FE loads pseudo-static `GET /v1/r100/pack/Rxx_spotcheck.js` (backend template)
//!   → templates live in memory / Redis (not 100 CDN files)
//!
//! Soft-only verify lane (score_weight=0); never commercial mint.

use serde_json::{json, Map, Value};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

pub const R100_TEMPLATES_ALGO: &str = "r100_pseudo_static_v1";
pub const R100_REDIS_PREFIX: &str = "gr:r100:pack:";
pub const R100_REDIS_SET: &str = "gr:r100:ids";

/// In-memory pack_id → meta JSON (`{s,p,dims}`).
#[derive(Debug, Clone, Default)]
pub struct R100TemplateCatalog {
    pub version: i64,
    pub algo: String,
    pub packs: HashMap<String, Value>,
}

impl R100TemplateCatalog {
    pub fn pack_count(&self) -> usize {
        self.packs.len()
    }

    pub fn pack_ids(&self) -> Vec<String> {
        let mut ids: Vec<String> = self.packs.keys().cloned().collect();
        ids.sort();
        ids
    }

    pub fn get(&self, pack_id: &str) -> Option<&Value> {
        self.packs.get(pack_id)
    }

    /// Load from `data/r100_templates.json` (generated by gen_random_ondemand_packs.js).
    pub fn load_from_path(path: impl AsRef<Path>) -> Result<Self, String> {
        let path = path.as_ref();
        let raw = fs::read_to_string(path).map_err(|e| format!("read {}: {e}", path.display()))?;
        Self::from_json_str(&raw)
    }

    /// Resolve CLI/env path that may be relative when process cwd ≠ repo root
    /// (lab gateway often starts with absolute binary path and cwd=/home/ubuntu).
    ///
    /// Order: absolute existing path → cwd-relative → candidates (static-dir sibling,
    /// exe-relative, CARGO_MANIFEST_DIR, /opt/green-v5).
    pub fn resolve_path(cli: impl AsRef<Path>, static_dir: Option<&Path>) -> Option<PathBuf> {
        let cli = cli.as_ref();
        if cli.is_absolute() {
            if cli.is_file() {
                return Some(cli.to_path_buf());
            }
            // absolute but missing — still try basename via candidates
        } else if cli.as_os_str().is_empty() {
            // fall through to candidates
        } else if cli.is_file() {
            return Some(cli.to_path_buf());
        }

        let file_name = cli
            .file_name()
            .map(|s| s.to_os_string())
            .unwrap_or_else(|| std::ffi::OsString::from("r100_templates.json"));

        for p in candidate_template_paths(static_dir) {
            if p.is_file() {
                return Some(p);
            }
            // allow candidate dir + same basename as cli
            if let Some(parent) = p.parent() {
                let alt = parent.join(&file_name);
                if alt.is_file() {
                    return Some(alt);
                }
            }
        }
        None
    }

    /// Load using resolve_path (cwd-independent).
    pub fn load_resolved(
        cli: impl AsRef<Path>,
        static_dir: Option<&Path>,
    ) -> Result<(Self, PathBuf), String> {
        let path = Self::resolve_path(cli.as_ref(), static_dir).ok_or_else(|| {
            format!(
                "r100_templates.json not found (cli={}, cwd={:?}); run scripts/gen_random_ondemand_packs.js",
                cli.as_ref().display(),
                std::env::current_dir().ok()
            )
        })?;
        let cat = Self::load_from_path(&path)?;
        Ok((cat, path))
    }

    pub fn from_json_str(raw: &str) -> Result<Self, String> {
        let v: Value = serde_json::from_str(raw).map_err(|e| format!("parse r100 templates: {e}"))?;
        let packs_v = v
            .get("packs")
            .cloned()
            .ok_or_else(|| "r100 templates missing packs".to_string())?;
        let obj = packs_v
            .as_object()
            .ok_or_else(|| "r100 packs must be object".to_string())?;
        let mut packs = HashMap::new();
        for (k, meta) in obj {
            if !is_r100_pack_id(k) {
                continue;
            }
            packs.insert(k.clone(), meta.clone());
        }
        if packs.is_empty() {
            return Err("r100 templates: zero valid Rxx_spotcheck packs".into());
        }
        Ok(Self {
            version: v.get("version").and_then(|x| x.as_i64()).unwrap_or(1),
            algo: v
                .get("algo")
                .and_then(|x| x.as_str())
                .unwrap_or(R100_TEMPLATES_ALGO)
                .to_string(),
            packs,
        })
    }

    /// Search common tree paths for templates SSOT.
    pub fn load_default() -> Result<Self, String> {
        Self::load_default_with_static_dir(None)
    }

    pub fn load_default_with_static_dir(static_dir: Option<&Path>) -> Result<Self, String> {
        for p in candidate_template_paths(static_dir) {
            if p.is_file() {
                return Self::load_from_path(&p);
            }
        }
        Err("r100_templates.json not found (run scripts/gen_random_ondemand_packs.js)".into())
    }

    /// Render executable pack JS (registerPack body) for pseudo-static HTTP.
    pub fn render_pack_js(&self, pack_id: &str) -> Result<String, String> {
        let meta = self
            .get(pack_id)
            .ok_or_else(|| format!("unknown_r100_pack:{pack_id}"))?;
        Ok(render_register_pack_js(pack_id, meta))
    }

    /// Pick pack id by stable seed (session/plan) — same lane as brain R pick.
    pub fn pick_pack_id(&self, seed: u64) -> Option<String> {
        let ids = self.pack_ids();
        if ids.is_empty() {
            return None;
        }
        let i = (seed as usize) % ids.len();
        Some(ids[i].clone())
    }

    pub fn status_json(&self) -> Value {
        json!({
            "ok": true,
            "algo": R100_TEMPLATES_ALGO,
            "catalog_algo": self.algo,
            "version": self.version,
            "pack_count": self.pack_count(),
            "redis_key_prefix": R100_REDIS_PREFIX,
            "redis_set_key": R100_REDIS_SET,
            "endpoint": "/v1/r100/pack/{pack_id}.js",
            "mode": "pseudo_static_templates",
            "note": "Brain schedules 1 R/tick; FE loads rt static + one template via API (Redis/memory)",
        })
    }
}

pub fn is_r100_pack_id(id: &str) -> bool {
    // R00_spotcheck .. R99_spotcheck (len 13)
    let b = id.as_bytes();
    b.len() == 13
        && b[0] == b'R'
        && b[1].is_ascii_digit()
        && b[2].is_ascii_digit()
        && id.ends_with("_spotcheck")
}

/// Render the same shape as gen_random_ondemand_packs.js pack files.
pub fn render_register_pack_js(pack_id: &str, meta: &Value) -> String {
    let json = serde_json::to_string(meta).unwrap_or_else(|_| "{}".into());
    format!(
        r#"/** R pack {pid} — pseudo-static template (backend) */
(function (g) {{
  "use strict";
  var RV = g.GRRandomVerify;
  if (!RV || typeof RV.registerPack !== "function") {{
    try {{ console.warn("[gr] load registry.random.rt.js before {pid}"); }} catch (e) {{}}
    return;
  }}
  RV.registerPack({pid_json}, {meta});
  g.__GR_R_PACK_LOADED__ = g.__GR_R_PACK_LOADED__ || {{}};
  g.__GR_R_PACK_LOADED__[{pid_json}] = 1;
  g.__GR_R_PACK_SOURCE__ = g.__GR_R_PACK_SOURCE__ || {{}};
  g.__GR_R_PACK_SOURCE__[{pid_json}] = "pseudo_static_api";
}})(typeof window !== "undefined" ? window : globalThis);
"#,
        pid = pack_id,
        pid_json = serde_json::to_string(pack_id).unwrap_or_else(|_| format!("\"{pack_id}\"")),
        meta = json
    )
}

fn candidate_template_paths(static_dir: Option<&Path>) -> Vec<PathBuf> {
    let mut out = Vec::new();
    if let Some(p) = gr_abi::env::get("R100_TEMPLATES") {
        out.push(PathBuf::from(p));
    }
    // Cwd-relative (works when service starts from repo root)
    out.push(PathBuf::from("data/r100_templates.json"));
    // static-dir is typically `<repo>/fe` → sibling `data/`
    if let Some(sd) = static_dir {
        if let Some(parent) = sd.parent() {
            out.push(parent.join("data/r100_templates.json"));
        }
        out.push(sd.join("data/r100_templates.json"));
        out.push(sd.join("../data/r100_templates.json"));
    }
    // Executable-relative: target/release/gr-service → ../../data
    if let Ok(exe) = std::env::current_exe() {
        if let Some(bin_dir) = exe.parent() {
            out.push(bin_dir.join("data/r100_templates.json"));
            out.push(bin_dir.join("../data/r100_templates.json"));
            out.push(bin_dir.join("../../data/r100_templates.json"));
            // Deploy layout: /opt/green-v5/bin/gr-service → /opt/green-v5/data/
            out.push(bin_dir.join("../data/r100_templates.json"));
        }
    }
    // Compile-time repo path (dev/lab builds)
    out.push(
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("../../../data/r100_templates.json"),
    );
    out.push(PathBuf::from("/opt/green-v5/data/r100_templates.json"));
    // De-dupe while preserving order
    let mut seen = std::collections::HashSet::new();
    out.retain(|p| {
        let key = p.to_string_lossy().to_string();
        seen.insert(key)
    });
    out
}

/// Flatten catalog packs to Redis SET payload list (for seed scripts).
pub fn redis_seed_entries(cat: &R100TemplateCatalog) -> Vec<(String, String)> {
    cat.packs
        .iter()
        .map(|(id, meta)| {
            (
                format!("{R100_REDIS_PREFIX}{id}"),
                serde_json::to_string(meta).unwrap_or_else(|_| "{}".into()),
            )
        })
        .collect()
}

/// Build a slim catalog map for ops (no full dims).
pub fn catalog_summary(cat: &R100TemplateCatalog) -> Value {
    let mut rows = Map::new();
    for id in cat.pack_ids() {
        if let Some(m) = cat.get(&id) {
            let dims_n = m
                .get("dims")
                .and_then(|d| d.as_array())
                .map(|a| a.len())
                .unwrap_or(0);
            rows.insert(
                id,
                json!({
                    "priority": m.get("p"),
                    "seed": m.get("s"),
                    "dims_n": dims_n,
                }),
            );
        }
    }
    json!({
        "algo": R100_TEMPLATES_ALGO,
        "pack_count": cat.pack_count(),
        "packs": rows,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pack_id_regex() {
        assert!(is_r100_pack_id("R00_spotcheck"));
        assert!(is_r100_pack_id("R99_spotcheck"));
        assert!(!is_r100_pack_id("R0_spotcheck"));
        assert!(!is_r100_pack_id("B10_hw_curves"));
    }

    #[test]
    fn render_contains_register() {
        let meta = json!({"s":0,"p":22,"dims":[{"d":"api_surface","ops":[]}]});
        let js = render_register_pack_js("R07_spotcheck", &meta);
        assert!(js.contains("R07_spotcheck"));
        assert!(js.contains("registerPack"));
        assert!(js.contains("pseudo_static"));
    }

    #[test]
    fn load_default_if_generated() {
        // CI may not have generated file; skip soft.
        if let Ok(c) = R100TemplateCatalog::load_default() {
            assert!(c.pack_count() >= 1);
            let id = c.pack_ids()[0].clone();
            assert!(c.render_pack_js(&id).unwrap().contains(&id));
        }
    }

    #[test]
    fn resolve_path_finds_repo_data_even_if_cwd_wrong() {
        // Simulate gateway start: relative cli path, no assumption on cwd.
        let cli = Path::new("data/r100_templates.json");
        // Prefer the workspace's physical browser-probe directory.
        let repo = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../..");
        let fe = repo.join("02-probe-analysis/probe/fe");
        let static_dir = if fe.is_dir() { Some(fe.as_path()) } else { None };
        let resolved = R100TemplateCatalog::resolve_path(cli, static_dir);
        if repo.join("data/r100_templates.json").is_file() {
            let p = resolved.expect("must resolve when repo data file exists");
            assert!(p.is_file(), "{p:?}");
            let cat = R100TemplateCatalog::load_from_path(&p).expect("load");
            assert!(
                cat.pack_count() >= 50,
                "expected full R100 catalog, got {}",
                cat.pack_count()
            );
        }
    }

    #[test]
    fn load_resolved_via_static_dir() {
        let repo = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../..");
        let fe = repo.join("02-probe-analysis/probe/fe");
        if !repo.join("data/r100_templates.json").is_file() {
            return;
        }
        let (cat, path) = R100TemplateCatalog::load_resolved(
            "data/r100_templates.json",
            Some(fe.as_path()),
        )
        .expect("load_resolved");
        assert!(path.is_file());
        assert!(cat.pack_count() >= 50);
        assert!(cat.get("R00_spotcheck").is_some());
    }
}
